ERCOL_URL = "https://www.johnlewis.com/" "ercol-for-john-lewis-shalstone-2-drawer-bedside-table/p2523085"
TOASTER_URL = "https://www.johnlewis.com/dualit-lite-4-slice-toaster-with-warming-rack/canvas-white/p231521950"
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 "
    "(KHTML, like Gecko) Version/15.0 "
    "Safari/605.1.15 "
)
BLOB_NAME = "prices.csv"
STORAGE_CONNECTION = "STORAGE_CONNECTION"
CONTAINER_NAME = "CONTAINER_NAME"
SENDGRID_API_KEY = "SENDGRID_API_KEY"
PRICE_COL = "Price"
DATE_COL = "Date"
ITEM_COL = "Item"
ALERT_EMAIL = "no_reply@32mt.uk"
